### ISSUE TITLE
Critical Game Crash

### ISSUE THREAD

**Issue by xNinjaRose** [Nider001/Borderlands-2-rebalance-mod#1]
Game crashes upon first cutscene with this mod executed,
`Fatal Error!
Address = 0x0 (Filename not found)`

I tried adding the cutscene disabler to the mod file, saved it and it didn't work with this mod, so I'd fix this critical crash issue with the knuckledragger cutscene where he steals his eye. 

Beside that, I'm sure it works, I picked up money, and where if it was still lv 50 scaled, itd be thousands but it was regular beginning game money

**Comment by Nider001** [comment]
Looks like you haven't followed the installation guide as needed. You are supposed to play in UVHM mode with the new saves.
